version: 2
updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: monthly
